name: Run Fixture Test
description: This action runs the uv-align tool on the specified fixture directory and compares the output with the expected output.
inputs:
  fixture-directory:
    description: 'The directory containing the fixture to test.'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Run tool on fixture
      run: |
        echo "Running tool on fixture directory..."
        uv run uv-align -y ${{ inputs.fixture-directory }}

        echo "Checking if the output matches the expected output..."
        diff ${{ inputs.fixture-directory }}/pyproject.toml ${{ inputs.fixture-directory }}/pyproject.toml.expected

        echo "Ensuring dependencies can be updated..."
        uv run uv-align -yu ${{ inputs.fixture-directory }}
      shell: bash
