name: Integration Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  integration-tests:
    name: integration-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v6

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - uses: javidahmed64592/actions-template-python/actions/setup/setup-uv-python@main
      - uses: javidahmed64592/actions-template-python/actions/setup/install-python-core@main

      - name: Verify installation
        run: uv run uva --help

      - name: Run tool (Project root)
        run: |
          uv run uva --check
          uv run uva -yu

      - name: Run Fixture Test - Sample One
        uses: ./.github/actions/run-fixture-test
        with:
          fixture-directory: tests/fixtures/sample-one

      - name: Run Fixture Test - Sample Two
        uses: ./.github/actions/run-fixture-test
        with:
          fixture-directory: tests/fixtures/sample-two

      - name: Run Fixture Test - Sample Three
        uses: ./.github/actions/run-fixture-test
        with:
          fixture-directory: tests/fixtures/sample-three
