name: Integration Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  integration-tests:
    name: Integration - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v6

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - uses: javidahmed64592/actions-template-python/actions/setup/setup-uv-python@main
      - uses: javidahmed64592/actions-template-python/actions/setup/install-python-core@main

      - name: Verify installation
        run: uv run uv-align --help

      - name: Run tool (Project root)
        run: uv run uv-align -y
